[package]
name = "stereocord"
version = "1.0.0"
edition = "2021"
description = "Signature-based stereo / high-bitrate patcher for Discord's Linux voice module"
license-file = "LICENSE"
repository = "https://github.com/DasPauluteli/stereocord"

[[bin]]
name = "stereocord"
path = "src/main.rs"

[dependencies]

[profile.release]
opt-level = 2
strip = true
